name: Run Unit Tests

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Install xmllint for test export
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests and generate JUnit report
      - name: Run unit tests
        run: npm run test:ci

      # Upload test results as an artifact
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results/results.xml

      # Upload coverage report as an artifact
      - name: Upload coverage report (Cobertura XML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/cobertura-coverage.xml

      - name: Extract coverage from Cobertura XML
        id: extract_coverage
        run: |
          COVERAGE=$(xmllint --xpath "string(//coverage/@line-rate)" coverage/cobertura-coverage.xml)
          COVERAGE_PERCENT=$(awk "BEGIN { printf \"%.0f\", $COVERAGE * 100 }")
          echo "coverage=${COVERAGE_PERCENT}" >> $GITHUB_OUTPUT

      - name: Extract test count
        id: extract_tests
        run: |
          TOTAL=$(jq '.numTotalTests' jest-report.json)
          echo "total=${TOTAL}" >> $GITHUB_OUTPUT

      - name: Create PR badge comment
        run: |
          echo "## ✅ Test & Coverage Report" > comment.md
          echo "![Tests](https://img.shields.io/badge/tests-${{ steps.extract_tests.outputs.total }}-blue)" >> comment.md
          echo "" >> comment.md
          echo "![Coverage](https://img.shields.io/badge/coverage-${{ steps.extract_coverage.outputs.coverage }}%25-brightgreen)" >> comment.md

      - name: Comment PR with badges
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment.md
